title:            Playground
description:     A place to play.
url:              http://trigonaminima.github.io/
paginate:         10

pygments:         true
permalink:        pretty
markdown:       redcarpet
rdiscount:
  extensions:     [smart]

# Theme specific settings
theme:            b
signoff:          Shivam Rana
facebook_appid:   
google_analytics: 
disqus_shortname: 

owner:
  name:           Shivam Rana
  avatar:         'http://www.gravatar.com/avatar/c9b959b3098d7c12ee8c389c817c91e8.png'
  bio:            'Another curious soul. Lives in Delhi. Interested in a lot of things - Science, Arts, History, Philosophy - basically everything around me and you.'

links: 
  - name:         Home
    url:          /
  - name:         Categories
    url:          /categories
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:trigonamin@gmail.com
  - name:         GitHub
    url:          http://github.com/TrigonaMinima