title: Playground
description: ""
url: https://trigonaminima.github.io
paginate: 1500
paginate_path: "/blog/page:num/"
permalink: "/:year/:month/:title/"

highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]

kramdown:
  input: GFM
  syntax_highlighter: rogue
  auto_ids: true


# For the feeds
name: Playground
author: Shivam Rana

plugins:
  - github-pages
  - jekyll-feed
  - jekyll-paginate

# Owner Settings
owner: Shivam Rana
avatar: 'http://www.gravatar.com/avatar/c9b959b3098d7c12ee8c389c817c91e8.png'
email: shivamrana95@yahoo.in
# bio: ''
twitter_username: TrigonaMinima
github_username: TrigonaMinima
lastfm_username: Shivamrana
stackoverflow: trigonaminima
linkdin_username: tminima
